duckdb -c "SET PRESERVE_INSERTION_ORDER=False; COPY (SELECT commit_timestamp, CASE WHEN \"DATA ELABORAZIONE\" IS NOT NULL
THEN CAST (\"DATA ELABORAZIONE\" AS DATE) ELSE CAST (TO_TIMESTAMP(commit_timestamp) AS DATE) END AS \"DATA ELABORAZIONE\", "REGIONE", "PROVINCIA", "COMUNE", \
CASE WHEN "COD_ISTAT_COMUNE" IS NOT NULL THEN "COD_ISTAT_COMUNE"  ELSE "CODISTAT" END AS COD_ISTAT_COMUNE, CAST (RESIDENTI AS INTEGER) AS RESIDENTI
 FROM read_parquet('parquet_files/*.parquet', union_by_name=True) ORDER BY \"DATA ELABORAZIONE\", REGIONE, PROVINCIA, COMUNE, COD_ISTAT_COMUNE) TO res.parquet (FORMAT 'PARQUET', COMPRESSION 'zstd')"

duckdb -c "SET PRESERVE_INSERTION_ORDER=False; COPY (SELECT \"DATA ELABORAZIONE\", "REGIONE", "PROVINCIA", "COMUNE", \
"COD_ISTAT_COMUNE", LAST (RESIDENTI ORDER BY commit_timestamp) AS RESIDENTI \
 FROM 'res.parquet' WHERE \"DATA ELABORAZIONE\" IS NOT NULL GROUP BY \"DATA ELABORAZIONE\", "REGIONE", "PROVINCIA", "COMUNE", "COD_ISTAT_COMUNE"  \
 ORDER BY \"DATA ELABORAZIONE\", REGIONE, PROVINCIA, COMUNE, COD_ISTAT_COMUNE) \
TO 'res2.parquet' (FORMAT 'PARQUET', COMPRESSION 'zstd')"